apiVersion: v2
name: sequiascope
version: 1.0.0
appVersion: 1.0.0
description: A Helm chart for SeqUIaSCOPE - Shiny application for genomic data visualization
keywords:
- sequiascope
- oncology
- genomic variants
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps-secure
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz