replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Main application container
sequiascope:
  image:
    repository: juraskovakaterina/sequiascope-app
    pullPolicy: Always
    tag: "1.0.0"
  extraEnv: {}
  resources:
    requests:
      memory: 5Gi
      cpu: 1
    limits:
      memory: 8Gi
      cpu: 8
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

# IGV container
igv:
  image:
    repository: juraskovakaterina/sequiascope-igv
    pullPolicy: Always
    tag: "1.0.0"
  extraEnv: 
    - name: HTTPS_PROXY
      value: http://proxy.muni.cz:3128
    - name: HTTP_PROXY
      value: http://proxy.muni.cz:3128
    - name: JAVA_TOOL_OPTIONS
      value: "-Duser.home=/root -Dhttps.proxyHost=proxy.muni.cz -Dhttps.proxyPort=3128 -Dhttp.proxyHost=proxy.muni.cz -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=localhost|127.0.0.1|*.cluster.local"
  resources:
    requests:
      memory: 5Gi
      cpu: 1
    limits:
      memory: 8Gi
      cpu: 1
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  appPort: 8080
  igvPort: 8081

networkPolicy:
  enabled: true

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host:
  tls:
    enabled: true
  auth:
    enabled: true
    username: "admin"
    password: ""
    existingSecret: "" # Name of existing secret to use (if set, username/password are ignored)

inputPersistence:
  enabled: true
  accessModes:
    - ReadWriteMany
  size: 100Gi
  storageClassName: ""
  existingClaim: ""

outputPersistence:
  enabled: true
  accessModes:
    - ReadWriteMany
  size: 100Gi
  storageClassName: ""

nodeSelector: {}

tolerations: []

affinity: {}
