{{- if and .Values.ingress.enabled .Values.ingress.auth.enabled (not .Values.ingress.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sequiascope.fullname" . }}-basic-auth
  labels:
    {{- include "sequiascope.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ printf "%s:%s" .Values.ingress.auth.username (bcrypt .Values.ingress.auth.password) | b64enc }}
{{- end }}
