apiVersion: v1
kind: Service
metadata:
  name: {{ include "sequiascope.fullname" . }}
  labels:
    {{- include "sequiascope.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: 8080
      protocol: TCP
      name: app
    - port: {{ .Values.service.igvPort }}
      targetPort: 8081
      protocol: TCP
      name: igv
  selector:
    {{- include "sequiascope.selectorLabels" . | nindent 4 }}
