{{- if and .Values.storage.enable (ne .Values.storage.server "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storage.name" . }}
  labels:
    cerit-cifs-secret: "yes"
    storage: {{ .Values.storage.server | regexFind "^[^/]*" }}
    share: {{ .Values.storage.server | regexFind "[^/]*$"  }}
data:
{{- if regexMatch "^[0-9]*$" .Values.storage.username }}
  mount_flags: {{ printf "username=%s,password=%s,uid=1000,gid=1000,nosetuids,vers=3.11,noserverino,domain=UCN" .Values.storage.username .Values.storage.password | b64enc | quote }}
{{- else }}
  mount_flags: {{ printf "username=%s,password=%s,uid=1000,gid=1000,nosetuids,vers=3.11,noserverino" .Values.storage.username .Values.storage.password | b64enc | quote }}
{{- end }}
type: Opaque
{{ end }}
